#!/bin/bash -e

VMADMIN_INSTALLED="$(mysql -uroot -ph4cker -sse "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = 'vmadmin')")"

if [ $VMADMIN_INSTALLED = 1 ]; then
  echo 'POSTINST: vmadmin schon eingerichtet...'
else
  echo 'POSTINST: richte Datenbank ein...'
  echo "CREATE USER 'vmadmin'@'localhost' IDENTIFIED BY 'h4cker';" | mysql -uroot -ph4cker
  echo "GRANT ALL PRIVILEGES ON * . * TO 'vmadmin'@'localhost';"        | mysql -uroot -ph4cker
  echo "FLUSH PRIVILEGES;"                                              | mysql -uroot -ph4cker
fi

echo 'POSTINST: befülle Datenbank...'

mysql -uvmadmin -ph4cker < /usr/share/fulla/db.sql

